### ISSUE TITLE
Question: What is the needed input data for the meshing function, and how to use the output.

### ISSUE THREAD

**Issue by MountainLabz** [Inspirateur/binary-greedy-meshing#5]
Seriously, understanding how this thing is used is a pain.
Some good documentation/tutorial useage would be greatly appreciated.

**Comment by Inspirateur** [comment]
Gotcha, I added some code comment in the minimal example for the input shape. The output is already specified in the README, could you detail a bit more what it is that you don't understand :) ? I'll answer any questions here and will update the README as necessary.

**Comment by MountainLabz** [comment]
I'm having a hard time understanding the input, which you fixed :) and then how to actually use the output. But I think the current readme is probably sufficient. I'm newer to rust, and the output was a bit confusing. But I now understand that you optimised the greedy mesher output to work with instanced quads as mentioned in the vericidium video.

**Comment by Inspirateur** [comment]
Yes, also the output data is pre-packed because you will need to pack it when sending it to the GPU otherwise it's going to take way too much bandwidth, I understand that this is a bit confusing but it's a necessary evil :p

Anyway I'm closing this issue but feel free to ask more questions if you struggle to use the crate !

**Comment by MountainLabz** [comment]
Thank you for your help :D
